### ISSUE TITLE
Detail view not found

### ISSUE THREAD

**Issue by DirtyF** [belazer/graphcms-algolia#1]
The demo works on https://codesandbox.io/s/kxxk9nolov but not on Netlify:

```gherkin
Given that I'm on the list view
When I click on a link to detail view
Then the detail view is not found
```

**Comment by belazer** [comment]
Working on it, seems to be a copy and paste issue, since netlify needs the `<Link>` component and codesandbox only `<a>`

**Comment by belazer** [comment]
Netlify build is running - should be fixed.
